export const enwords = [
    'word', 'in', 'at', 'thought', 'fell', 'he', 'I', 'for', 'window', 'system', 'key', 'sky', 'every',
    'science', 'time', 'good', 'right', 'wrong', 'over', 'music', 'down', 'front', 'of', 'mine', 'his', 
    'break', 'hot', 'cold', 'rain', 'color', 'white', 'energy', 'into', 'give', 'so', 'but', 
    "with", 'simple', 'easy', 'why', 'home', 'work', 'office', 'number', 'sleep', 'awake',
    "tired", 'wait', 'call', 'country', 'Peter', 'quick', 'constantly', 'strong', 'weak', 'trust',
    'me', 'bad', 'asked', 'came', 'did', 'task', 'books', 'find', 'nice', 'add', 'trip', 'travel', 'you',
    'have', 'had', 'cat', 'where', 'move', 'to', 'country', 'go', 'toward', 'beach', 'Miami', 'wine', 'out',
    'gone', 'done', 'heart', 'attack', 'case', 'computer', 'black', 'body', 'respect', 'this', 'that', 'these',
    'bold', 'word', 'fast', 'quick', 'fat', 'skin', 'sorry', 'no', 'more', 'else', 'child', 'children', 'being',
    'time', 'run', 'service', 'job', 'work', 'was', 'will', 'then', 'under', 'upon', 'free', 'man', 'woman',
    'receive', 'letter', 'true', 'false', 'type', 'kind', 'so', 'but', 'mad', 'at', 'me', 'him', 'her', 'is', 'us', 'not', 'area', 'code', 'address', 'mine', 'his', 'her', 'our', 'feelings', 'beauty', 'father', 'mother', 'tonight', 'tomorrow', 'war',
    'zone', 'west', 'north', 'east', 'from', 'for', 'buy', 'as', 'twice', 'once', 'time', 'sugar', 'salt', 'far', 'tall',
    'than', 'what', "don't", 'say', 'said', 'game', 'last', 'chance', 'take', 'took', 'stop', 'step', 'school', 'learn', 'music',
    'wise', 'intelligent', 'smart', 'phone', 'number', 'air', 'summer', 'spring', 'winter', 'fall', 'sea', 'full', 'hungry',
    'whom', 'whose', 'between', 'inside', 'into', 'in', 'foward', 'look', 'clock', 'among', 'amount', 'love', 'talk', 'English',
    'Spanish', 'John', 'Kevin', 'new', 'old', 'sense', 'notice', 'books', 'dictionary', 'words', 'fire', 'set', 'play',
    'train', 'car', 'big', 'screen', 'recording', 'walking', 'eating', 'myself', 'yourself', 'themselves', 'own', 'owner', 'town',
    'downtown', 'sun', 'sunny', 'weather', 'water', 'rain', 'clouds', 'umbrella', 'because', 'did', 'it', 'space', 'hope', 'wait',
    'outside', 'happiness', 'sad', 'ocean', 'city', 'America', 'person', 'people', 'king', 'queen', 'browse', 'internet', 'data',
    'information', 'mining', 'related', 'couple', 'wife', 'husband', 'son', 'daughter', 'technical', 'chain', 'bus', 'system', 
    'hear', 'listen', 'command', 'police', 'truck', 'plane', 'fly', 'trip', 'advice', "shouldn't", 'seen', 'try', 'trial', 'need',
    'to', 'get', 'understand', 'common', 'none', 'nothing', 'stuff', 'change', 'switch', 'write', 'key', 'power', 'pull', 'close',
    'taller', 'bigger', "isn't", 'will', 'be', 'kind', 'off', 'service', 'can', 'cannot', 'there','here', 'return', 'call', 'pass',
    'video', 'audio', 'sound', 'repeat', 'playing', 'around', 'bread', 'meal', 'some', 'food', 'each', 'every', 'everybody', 'someone',
    'credit', 'card', 'money', 'cash', 'pay', 'payment', 'behind', 'closed', 'market', 'place', 'reveal', 'coming', 'soon', 'after',
    'before', 'street', 'won', 'touch', 'keep', 'whatever', 'any', 'anything', 'anyone', 'nobody', 'lie', 'rest', 'meter', 'kilometer',
    'were', 'went', 'miles', 'away', 'left', 'bye', 'by', 'position', 'angle', 'math', 'thought', 'tough', 'remember', 'remind',
    'memory', 'mind', 'care', 'carefully', 'knock', 'goal', 'sport', 'ball', 'basketball', 'football', 'baseball', 'soccer', 'league',
    'justice', 'hero', 'heroes', 'save', 'performance', 'features', 'main', 'stream', 'groud','garden', 'flower', 'sky', 'heaven',
    'want', 'wish', 'land', 'history', 'storm', 'snow', 'snowing', 'ugly', 'thank', 'now', 'cause', 'always', 'mouse', 'knife',
    'knives', 'kitchen', 'cook', 'cooking', 'master', 'grade', 'scholar', 'universe', 'theory', 'law', 'decision', 'view', 'point',
    'page', 'turn', 'worst', 'sell', 'store', 'use', 'user', 'system', 'process', 'long', 'strong', 'weak', 'eyes', 'nose', 'mouth',
    'week', 'month', 'days', 'years', 'century', 'center', 'middle', 'national', 'channel', 'challenge', 'fun', 'funny', 'bored',
    'boring', 'outgoing', 'please', 'spot', 'hit', 'again', 'hurry', 'dash', 'racing', 'homework', 'teacher', 'fireman', 'loyalty',
    'bright', 'shine', 'dark', 'soul', 'believe', 'rock', 'trouble', 'manage', 'coach', 'skill', 'ghost', 'sing', 'shoulder', 
    'never', 'often', 'frecuency', 'pencil', 'pen', 'chat', 'table', 'row', 'columns', 'Europe', 'Joseph', 'balance', 'catch','bot',
    'robot', 'filter', 'miss', 'faith', 'sight', 'sure', 'make', 'chef', 'period', 'success'  
] 