export const eswords = [
     'carro', 'azul', 'rojo', 'zapato', 'conciencia', 'pelota', 'lengua', 'jugada', 'juego',
     'emoción', 'carta', 'palabra', 'son', 'tu', 'estado', 'en', 'comida', 'sin', 'ellos', 
     'nosotros', 'no', 'si','y', 'piensa', 'tan', 'grande', 'grupo', 'mujer', 'hombre', 'con', 
     'saber', 'la', 'los', 'su', 'de', 'casi', 'tiempo', 'rápido', 'mí','nombre', 'poder', 
     'dinero', 'economía', 'silla', 'muy', 'gran', 'trabajo', 'lógica', 'situación', 'facilidad', 
     'texto', 'que','excluye', 'tanto', 'mucho', 'poco', 'guerra', 'paz', 'armonía', 
     'valor', 'inteligencia', 'cabeza', 'líquida', 'girasol', 'hermano', 'padre', 
     'madre', 'escuela', 'aprender', 'aprende', 'construir', 'Juan', 'María', 'Pedro', 'sabiduría', 'come', 'pescado', 'agua', 'cielo', 'anaranjado', 'noche', 'experiencia', 'importante', 'París', 'ciudad', 'país', 'ciudadano', 'es', 'un', 'profesión', 'universidad', 'para', 'comer', 'concepto',
     'rapidámente', 'constantemente', 'definidamente', 'conteo', 'minutos', 'pasa', 
     'distraerse', 'atención', 'familia', 'padre', 'Antonio', 'Patricia', 'Ana', 'todos', 'saltar', 'ejercicio', 'policía', 'canción', 'música', 'género', 'mantener', 'computadora', 'vida', 'tierra', 'planeta', 'estrella', 'medicina', 'doctor', 'Santiago', 'la', 'los', 'son', 'sus','mal', 'cosa', 'sin', 'casa', 'tiene', 'Luis', 'come', 'pasa', 'agua', 'salud', 'toma', 'bebida', 'sala', 'galería', 'palabra', 'hasta',
     'pensar', 'ver', 'ciencia', 'vida', 'Mateo', 'visión', 'acción', 'noche', 'coche', 'luz', 'claro', 'banco',
     'pantalla', 'pato', 'todo', 'del', 'eso', 'esa', 'esos', 'ya', 'vía', 'norte', 'sur',  'este', 
     'menos', 'lógica', 'yo', 'él', 'ella', 'ellos', 'soy', 'somos', 'una', 'un', 'unos', 'gas', 'version', 
     'camina', 'aire', 'viento', 'fuego', 'arena', 'playa', 'sol', 'cielo', 'nubes', 'verde', 'negro', 'problema', 'aquí', 'nuestro',
     'capital', 'país', 'continente', 'región', 'escribir', 'pensar', 'caminar', 'cantando', 'pensando', 'jugar', 'animación', 'lógica', 'emociones', 'experiencias', 'olvidar', 'con', 'hasta', 'nosotros', 'en', 'entre', 'medio', 'ellos', 'suyo',
     'mio', 'entra', 'entró', 'vigilar', 'ver', 'mira', 'escucha', 'atenta', 'hermana', 'como', 'puede', 'poder', 'oido', 'cabeza',
     'vivos', 'seres', 'humanos', 'consciente', 'cartera', 'carta','ambos', 'varios', 'por', 'que', 'cual', 'cuando', 'quien',
     'menos', 'poco', 'bastante', 'o', 'y', 'regular', 'alto', 'bajo', 'sonido', 'brillo', 'brillante', 'oscuro', 'nocturno', 'Marcos',
     'Pedro', 'José', 'imagina', 'creatividad', 'creativo', 'felicidad', 'feliz', 'calcular', 'tristeza', 'alegría', 'momento',
     'pasajero', 'futuro', 'grandioso', 'maravilloso', 'orden', 'desorden', 'amarillo', 'cuerda', 'cadena', 'diente', 'boca',
     'ojos', 'ama', 'amor', 'alma', 'creer', 'técnica', 'constante', 'variable', 'noticia', 'nuevo', 'conocimiento', 'origen', 'viento', 'asiento', 'sentarse', 'tanto', 'casi', 'caso', 'juicio', 'luz', 'sol', 'soleado', 'nube', 'nublado', 'pista',
     'antes', 'despúes', 'porque', 'lado', 'ocurre', 'secreto', 'discreto', 'guardar', 'lealtad', 'dominio', 'sobre', 'control',
     'reinado', 'mundano', 'poderoso', 'ciencia', 'sabio', 'herramienta', 'estudia', 'escalera', 'construcción', 'bloques',
     'tierra', 'vista', 'navegar', 'velas', 'barco', 'canción', 'artista', 'cantar', 'artístico', 'pintura', 'dibujo', 'artes',
     'baile', 'coreografía', 'ensayo', 'ensayar', 'micrófono', 'presentación', 'anónimo', 'privacidad', 'virtual', 'servidor',
     'identidad', 'simple', 'complejo', 'proeso', 'hilo', 'mecánico', 'manual', 'automático', 'máquina', 'tomar', 'beber', 'alcohol',
     'dormir', 'descanso', 'vacaciones', 'navidad', 'semana', 'días', 'horas', 'minutos', 'segundos', 'tiempo', 'teoría', 'ley',
     'hipótesis', 'método', 'pasos', 'valores', 'principios', 'único', 'irrepetible', 'tener', 'posesiones', 'riquezas', 'clase', 'jardín', 'flores', 'rosa', 'plantas', 'charlar', 'charla', 'discutir', 'debate', 'puntos', 'bienestar', 'severo', 'leve',
     'manipular', 'manipulando', 'pensamiento', 'crítico', 'coincidencia', 'gemelos', 'hermanos', 'familia','pariente', 'cercano',
     'apoyo', 'perseverancia', 'tolerancia', 'prudencia', 'contraste', 'comparar', 'opuestos', 'polos', 'magnético', 'rotación', 
     'traslación', 'movimiento', 'circular', 'eje', 'propio', 'atmósfera', 'lluvias', 'relámpagos', 'estrellas', 'iluminado', 'negro',
     'super', 'gigante', 'tamaño', 'cuerda', 'saltar', 'forma', 'disponible', 'figura','lados', 'espeso', 'agudo', 'grave',
     'semántica', 'etiqueta', 'idioma', 'hablado', 'mayor', 'base', 'altura', 'anchura', 'definir', 'biologia', 'pareja', 'parecido',
     'las', 'los', 'metro', 'distancia', 'kilómetro', 'lejano', 'cerca', 'millas', 'recorrido', 'desplazamiento', 'instante',
     'agilidad', 'equilibrio', 'mantenimiento', 'creación', 'compra', 'utilidad', 'tiene', 'carne', 'comestible', 'asado', 'astucia',
     'permiso', 'permitir', 'amistad', 'amigos','par', 'manzana', 'fruta', 'pera', 'posición', 'superior', 'inferior', 'nota', 'calificaciones', 'grado', 'escuela', 'carrera', 'profesional', 'ropa', 'moda', 'zapatos', 'nombre', 'apellido', 'veloz', 'unido',
     'estados', 'rio', 'cascada', 'laguna', 'bosque', 'parque', 'nacional', 'providencia'


]